### PR TITLE
Changed namespace for the utility class UrlUtility

### PR DESCRIPTION
**Pull request by biogenez**
With the exception of class "UrlUtility", all other utility classes have namespace "OfficeDevPnP.Core.Utilities".

### CODE REVIEW

**Comment by biogenez** [comment]
From [Framework Design Guidelines](https://msdn.microsoft.com/en-us/library/dn169395(v=vs.110).aspx): 
DO NOT put extension methods in the same namespace as the extended type unless it is for adding methods to interfaces or for dependency management.

**Comment by VesaJuvonen** [comment]
thx Alexander, we'll get this included, but will do this with deprecation of the old extension method to avoid breaking changes. We'll remove then the deprecated method in 2 months. Will be processed soon.

**Comment by biogenez** [comment]
Thank you for response

**Comment by jansenbe** [comment]
I've not implemented the deprecation as that would be a too impactful change in comparison with the risk of breaking backwards compatibility.

**Pull request merged**
