### PR TITLE
Update XMLPnPSchemaV201508Formatter.cs - Issue #236

### PR DESCRIPTION
**Pull request by ozmav**
Replace &= with |= to allow bitwise or to aggregate discrete audit mask values into the models AuditSettings.AuditFlags property.

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
Thx ozmav,
we'll have a look on this during upcoming days. Change is small, but we want to test it properly. Looks absolutely valid based on the first glance. thx for your contributions. Would also suggest to update your GitHub profile with your actual name, so that we can provide you credits as part of the January release notes.

**Comment by PaoloPia** [comment]
Hi ozmav,
Could you please target the dev branch instead of the master branch? Thank you.
I will close this one in the meantime.

**Comment by PaoloPia** [comment]
BTW, to make it easier... I applied the same change directly in the dev branch, and you will be still credited for what you have done. Thanks.

**Comment by VesaJuvonen** [comment]
Hi Ozmav,
Would also suggest to update your GitHub profile with your actual name, so that we can provide you credits as part of the January release notes. Obviously if nothing else, we'll add a link to your GitHub profile without your real name.

**Pull request closed without merging**
