### PR TITLE
Add support for Reused and Deprecated Terms during provisioning import and export.

### PR DESCRIPTION
**Pull request by rgylesbedford**
Add support for Reused and Deprecated Terms during provisioning import and export. Includes tests to ensure reusable terms can be created.

### CODE REVIEW

**Comment by erwinvanhunen** [comment]
Hi! 

Thank you so much for your submission! We have a minor issue though, and that is that you are changing the schema XSD file. We have a separate repository available at https://github.com/officedev/pnp-provisioning-schema. Please make another pull request with just the schema changes to the experimental branch there. The moment we accept those changes there and merge that change into core, we will merge this pull request to the core library. We're sorry for the hassle. We will leave this PR open for now, until the schema changes has been merged into core.

**Comment by rgylesbedford** [comment]
Hi Erwin,

I already have an open pull request against the experimental branch of [PnP-Provisioning-Schema](https://github.com/officedev/pnp-provisioning-schema). See [Pull Request #41](https://github.com/OfficeDev/PnP-Provisioning-Schema/pull/41)

**Comment by VesaJuvonen** [comment]
Hi Roydon, thanks for pull request. Schema change was just processed on the other side and it will be included in the new schema version which will be provided for review for the community during this week. Since we want to also include other schema changes together with this one, we will postpone processing of this pull request until the schema update has been reviewed and approved. This means that we are targeting to get this processed for the January master merge.

**Comment by PaoloPia** [comment]
Hi Roydon, let me add to this thread that for January master merge we will target the new 2015-12 schema version, which already includes your suggested changes. Thus this PR will have to be updated to target the upcoming new schema formatter for version 2015-12. I will take care of that in the upcoming days, after the november master merge.
Thanks for your support and contribution.

**Comment by VesaJuvonen** [comment]
Hi Roydon,
new schema will be included in the Dev branch starting from next week, so that we can proceed with this pull request.

**Comment by VesaJuvonen** [comment]
thx Roydon, with the latest schema changes, this PR is no longer valid, but since you raised this on our attention, will give you absolutely credits on the contribution for this one in the January release notes. Thx for your contribution.

**Pull request closed without merging**
