### PR TITLE
Added functionality to get Field Exists by Id with Search In Site Hierarchy

### PR DESCRIPTION
**Pull request by martinlingstuyl**
Many Extension methods have a 'search in site hierarchy' argument. 
I added it for the FieldExistsById check. Comes in handy now and then.

### CODE REVIEW

**Comment by martinlingstuyl** [comment]
By the way, I made a typo in the branch name and the first commit. It should of course be FieldExistsById, not FieldById. I amended the commit name.

**Comment by VesaJuvonen** [comment]
Hi martinlingstuyl, thanks for your contribution, looks good, but we'll double check. For giving you proper credits on this in our monthly call, would suggest to update your name in the GitHub profile... unless you want to stay anonymous.

**Comment by martinlingstuyl** [comment]
Thanks, did just update my profile.

**Comment by jansenbe** [comment]
Hey Martin,

I've manually implemented your proposed change but used a slightly different approach. I'll close this PR now but you'll get credits for this change in our monthly communications.

**Comment by martinlingstuyl** [comment]
Hi Bert,
Never mind, I'm interested to know how you pulled it off.
Martin

On 03 Jun 2016, at 17:00, Bert Jansen <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey Martin,

I've manually implemented your proposed change but used a slightly different approach. I'll close this PR now but you'll get credits for this change in our monthly communications.

-

**Comment by martinlingstuyl** [comment]
Ah, I see.. You broadened the scope to include GetFieldById...

Awesome!



On 03 Jun 2016, at 17:00, Bert Jansen <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey Martin,

I've manually implemented your proposed change but used a slightly different approach. I'll close this PR now but you'll get credits for this change in our monthly communications.

-

**Pull request closed without merging**
