### PR TITLE
Added support for custom token definitions via external providers

### PR DESCRIPTION
**Pull request by artokai**
Currently the provisioning engine does not allow defining custom token definitions.  I made a change to allow this through the existing Template.Providers -section.

After the TokenParser has been created the engine now scans all defined providers and checks if they implement the new IProvisioningExtensibilityTokenProvider interface. If they do, custom tokens provided by the provider are added to the TokenParser.

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
Hi Arto,
thanks for this and sorry for the delay for processing the pull request. We just had a core team meeting to process pull requests one by one and checked this one as well. This is absolutely great implementation and could be merged in without any issues - really nicely done. Only thing we started to think is that actual use case or business scenario for the change - which is why we now further delayed processing it. 

It could be simply that we do not see the use case, so we would highly appreciate additional details on how or why custom tokens is needed. Like said - this is just to understand the actual business requirement behind the change, so that we do not just evolve the technical implementation for the sake of doing that.

Thanks for the additional information advance.

**Comment by artokai** [comment]
Hello,

The particular use case I had in my mind was deployments to different environments (dev, staging, test, production, etc..). In different environments you might need to set up things a little bit differently. For example if you have embedded a link to a provider hosted SharePoint AddIn using Content Editor WebPart, that link might be different in each of the environments.

Currently you can already provide parametrized tokens to ProvisioningEngine via the template parameters. But if you would like to fetch these parameters for example from a SharePoint list, then you  could do this by writing a custom TokenProviderExtension. 

The benefit of having a custom TokenProvider is that it would work both when applying the template from powershell (Admin / Initial installation scenario) or from a custom SharePoint Addin (Self Service Site creation scenario)

**Comment by VesaJuvonen** [comment]
Thanks Arto, looks really good and business scenario does make sense. Due however small resourcing challenges during this month, we will postpone processing this PR fully for the January master merge to avoid any surprises or other issues.

**Comment by VesaJuvonen** [comment]
Hi Arto,
we are looking into testing this one properly starting from next week. Sorry for the delay with this one and thx for the contribution.

**Comment by artokai** [comment]
No problem!
Let me know if you need any help with testing or want me to provide additional unit tests etc..

**Comment by erwinvanhunen** [comment]
Hi!

I'm looking into this PR, due to the age, github reports that there merge conflicts to handle. Can you help us out and retrieve the latest dev branch, merge that with this branch and resolve the conflicts? Then it's just a matter of syncing this branch again with your github repo to update this PR.

Thanks!

**Comment by artokai** [comment]
Hi!

I synced the feature-branch with the current dev-branch and resolved the conflicts. 

I also slightly modified the AddExtendedTokens-function a bit to make it more inline with the already existing ProvisionObjects-function. They now contain identical configuration and error handling.

**Comment by erwinvanhunen** [comment]
Hi! All merged now. Thank you for contribution!

**Pull request merged**
