### PR TITLE
provisioning engine - view ContentTypeId and DefaultForContentType attributes support

### PR DESCRIPTION
**Pull request by ivanvagunin**
Added support for View ContentTypeId and DefaultForContentType attributes support

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
thx Ivan, let's target this for the March release.

**Comment by PaoloPia** [comment]
Hi Ivan, I'm checking the PR. I have just a question for you: in line 414 you use the contentTypeID variable, which could be null. In that case, if we have the DefaultViewForContentType attribute, but somehow we miss the ContentTypeID attribute, the could could fail. Thus, I would add a check for NULL against the contentTypeID variable, before using it. And in case of a NULL value, I would skip the whole "Default for content type" block. Do you agree? Thanks.

**Comment by ivanvagunin** [comment]
Hi Paolo, thanks for the finding. I totally agree on that. However I just realized that the 414 in not needed at all there, since it has nothing to do with setting DefaultViewForContentType property. Not sure why it was there before... So I just removed it and NullReference exception is not a threat any more.

**Comment by PaoloPia** [comment]
Great, good catch! :-) ... Merged! Thank you.

**Pull request merged**
