### PR TITLE
xml zip package provider for provisioning engine

### PR DESCRIPTION
**Pull request by ivanvagunin**
XMLZipPackageTemplateProvider allows to read/write XML site templates, content files and referenced files into single zip archive file.

### CODE REVIEW

**Comment by PaoloPia** [comment]
Hi Ivan, it looks a really interesting capability. We will look into it and we will try to merge it by the next monthly release. Thank you!

**Comment by PaoloPia** [comment]
Hi Ivan,
I looked into it, and it is really a great contribution, as well as a brilliant idea! Thank you!

What if we make it available not only for storing files on the file system? For example, we could use it for the PnP Partner Pack, where we store files on a SharePoint library. If you are not in rush to have this capability in the core library, I would like to do some refactoring, together with you if you can, to support any persistence storage (File System, SharePoint, and Azure Blob Storage). I would also like to create a dedicated test class.
What do you think?

Thanks.

**Comment by ivanvagunin** [comment]
Hi Paolo,

I am glad you like the idea. My main target is to create a way to develop and distribute site templates for provisioning engine easily (nowadays we have few templates that contains more than 30 files, so it becomes messy). I was thinking about something similar to "old good" WSP, a package that includes not only templates, but content files and extensibility providers DLLs. So developer can just "compile" this kind of package and give it to admin to "deploy". 
Zip provider is a first step and there is absolutely no rush on this merge. I like the idea to support other storage types, I was thinking of it too. So let's do the refactoring I can help of course.

**Comment by PaoloPia** [comment]
Ok, great! Let's do that after the master merge. Thus, I'll be back to this next week. Thanks, Paolo.

**Comment by PaoloPia** [comment]
Ivan, sorry for not being back on this topic earlier. We, as the Core Team, are thinking about using Open XML instead of ZIP files. We will keep you, and the entire community, updated. I will close this PR, even if we totally get its value and we really appreciate your efforts, which brought us to think about Open XML. Of course, you will be credited for what you did. Thank you.

**Comment by VesaJuvonen** [comment]
thx Ivan also from my behalf. This PR has initiated excellent discussion and we absolutely need this capability to manage templates, so that we can work on them more easily, like you mentioned in your comments as well. We are looking into using OpenXML for this, to align with the other SP packaging and we would have anyway needed to have some sort of an manifest file in zip to have details on content... this is natively in OpenXML.

Implementation will be implemented as optional capability, so that you can still access and manipulate serialized templates manually, if needed.

**Comment by ivanvagunin** [comment]
Hi Paolo, Vesa,

Thanks for response. Using OpenXML seems to be a good idea to me (though I am not much familiar with the format). At the moment we are using Zip provider in one of the projects and got very positive feedback on that from the developers. So we'll continue using that for now to get more feedback and new ideas. I agree that there is no point to put Zip provider to Core lib at this point, I'll refactor it as "external" lib and put to my github repo, if anyone wants to try it.

Thanks and looking forward to see OpenXML provider )

**Pull request closed without merging**
