### PR TITLE
PageExtensions.AddWikiPage: removed hardcoded url and handle existing page

### PR DESCRIPTION
**Pull request by sven-pohl**
- Removed hard coded URL path "sitepages"
- Return of server relative URL instead list relative URL
- Return site relative URL if page already exists

### CODE REVIEW

**Comment by jansenbe** [comment]
Hi Sven,

We discussed this PR in our core team meeting and would like to better understand the need for this change. Can you provide us more insight?

If we'll decide to take in the change we'll anyhow change the implementation as the current one does mean we'll return a different method output which we consider as being a breaking change.

**Comment by sven-pohl** [comment]
Hi Bart,

that this is a change which may have impact on existing implementations is absolutely correct.

My main intention for the change is to get rid of the hardcoded return value.
In my own project (where I use the OfficeDevPnP), I use a different library than "siteassets", but the current code returns this because auf the hard coded implementation, so one has to make a string replacement of the returned URL.

Doing that, I found that is more helpful to return the server relative URL like nearly all other functions which return an Url to an SP Element. I assume, that like in my project, adding the page is the first thing to do before one starts adding WebParts, HTML, etc. All these functions use a server relative URL as an input parameter. With the change I did, the function fits better to the other functions, which are already available in this area.

**Comment by sven-pohl** [comment]
If you want to change the implementation, I suggest to create a the function as "EnsureWikiPage" because of the handling if a page already exists.

**Comment by VesaJuvonen** [comment]
thx Sven, we'll do final testing on this and will get it included.

**Comment by jansenbe** [comment]
Manually merged this + followed the EnsureWikiPage suggestion. Thx Sven.

**Pull request closed without merging**
