### PR TITLE
Added the search results page setting at web level

### PR DESCRIPTION
**Pull request by gautamdsheth**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | yes
| New sample?      | no
| Related issues?  | n/a

#### What's in this Pull Request?

Added the ability to set the search results page url of the web. Until now, we are able to only set the search settings at the site collection level. Now, using this we would be able to redirect search results of the subsite to a particular page.

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
Hi gautamdsheth,
seems that the CLA has not been signed, which is required before we can process any PRs in all of the MS repositories. You can sign CLA electronically from https://cla.microsoft.com.

**Comment by gautamdsheth** [comment]
Hi @VesaJuvonen , i have already signed the CLA. 
[Signed-on-Paper_805a9fbf-ae5f-4042-97a2-a8d0ec5848eb.pdf](https://github.com/OfficeDev/PnP-Sites-Core/files/301981/Signed-on-Paper_805a9fbf-ae5f-4042-97a2-a8d0ec5848eb.pdf)

**Comment by VesaJuvonen** [comment]
We have moved to fully electronic CLAs while back, so that signing has to happen again with the electronic forms. Form is exactly the same, but unless signing happens electronically, GitHub automation with CLAs is not working properly.

**Comment by jansenbe** [comment]
Thx @gautamdsheth, this was a good change and I've merged it.

**Pull request merged**
