### PR TITLE
Proposed solution to Bug #165

### PR DESCRIPTION
**Pull request by luismanez**
Bug fixed with this pull request. Tested.

### CODE REVIEW

**Comment by erwinvanhunen** [comment]
Good catch!

**Comment by luismanez** [comment]
Thanks! glad to help.

**Comment by VesaJuvonen** [comment]
Sorry Luis for missing this one first from the notes - All release notes have been updated accordingly and thanks for letting us know. We definitely want to provide credit for those who have helped us and participate on this community effort.

**Comment by luismanez** [comment]
Thanks Vesa! I can't find my name in the release blog post yet (dev.office.com). Anyway, no worries, I hope to do a new contribution in the next month. Thanks again!!

**Comment by VesaJuvonen** [comment]
Fixed now - helps if you press Publish after edits. Sorry for the delay. Now listed. We'll do some additional promotion for this still in upcoming days. You are also listed in the monthly community call presentation and call starting in 10 minutes.

**Comment by luismanez** [comment]
see it now :) many thanks Vesa, really appreciate it.

**Pull request merged**
