### PR TITLE
Added functionality: Convert folder to document set

### PR DESCRIPTION
**Pull request by martinlingstuyl**
As a rule of thumb: one should always use document sets instead of folders. But if folders were used, whether by malicious users or (now) fired developers, you might want to convert them.

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
Hi martinlingstuyl,
tested this just now (sorry for the delay), but getting "Additional information: Only 'Include' and 'IncludeWithDefaultProperties' methods are supported" exception on the following line:

listItem.EnsureProperty(f => f["ContentTypeId"]);

Capability is interesting, even though would not call document sets as recommended capability on top of the folders. This is not that black and white statement. Anything I'm missing here? We could obviously refactor some of the code in the PnP Core team, but would rather get needed changes done by the contributors.

**Comment by okms** [comment]
Interesting! I usually have the exact opposite recommendation. Use folders rather than document sets, but preferably neither.

**Comment by martinlingstuyl** [comment]
Ok, weird, I could swear to having tested this properly. Anyhow, I changed the EnsureProp statement to a load statement, all should work as expected now. (I tested it, :))

**Comment by VesaJuvonen** [comment]
thx martinlingstuyl, will double check and merge in.

**Comment by VesaJuvonen** [comment]
Hi Martin,
sorry for small delay on this. Getting it merged, so thanks for the contributions. I'll do a few updates on the comments, since even though in some scenarios document sets are useful, we can't really generally state that they are best practice on top of folders. That really depends on business and functional requirements of the deployment, so we'll need to avoid black-and-white statements like this.

**Comment by martinlingstuyl** [comment]
Hi Vesa,
Of course I was just teasing a bit with my statement about firing developers using folders :) so it's fine by me if you edit it.

**Pull request merged**
