### PR TITLE
Fixed issue with overwriting HomePage (not possible to delete HomePage)

### PR DESCRIPTION
**Pull request by SchauDK**
If Overwrite is True on a Page that is already HomePage, it cannot be deleted. Hence it isn't overwritten.
Eg.

      <pnp:Pages WelcomePage="{site}/SitePages/Home.aspx">
        <pnp:Page Url="{site}/SitePages/Home.aspx" Overwrite="true" Layout="TwoColumnsHeader">
          <pnp:Security>
            <pnp:BreakRoleInheritance CopyRoleAssignments="false" ClearSubscopes="false" />
          </pnp:Security>
        </pnp:Page>
      </pnp:Pages>

### CODE REVIEW

**Comment by erwinvanhunen** [comment]
Great addition! Thank you!

**Comment by artokai** [comment]
I believe that this line found later in the same function no longer works since the web.RootFolder is no longer loaded:

```
url.Substring(web.RootFolder.ServerRelativeUrl.Length);
```

At least we started experiencing property not loaded exceptions for folder.ServerRelativeUrl property after switching to the latest nugget release.

I haven't yet had the time to test or investigate this any further...

**Comment by SchauDK** [comment]
Yep, 

    web.EnsureProperties(w => w.ServerRelativeUrl, w => w.RootFolder.WelcomePage);

is not loading the WelcomePage as expected.

There's already a PR for it here https://github.com/OfficeDev/PnP-Sites-Core/pull/169

**Comment by artokai** [comment]
Great work for having a fix for this already! Thanks!

**Pull request merged**
