### PR TITLE
Added capability to handle migration of reused managed metadata terms

### LINKED ISSUE #506: Term Reuse
Term reuse causes error "Failed to read from or write to database"

### PR DESCRIPTION
**Pull request by eric-scott-owens**
| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | yes
| New sample?      | no
| Related issues?  | fixes #506

#### What's in this Pull Request?

Add the ability to mark re-used terms in templates with the property IsReused="TRUE". Fields thus marked first check if the term already exists in the term store. If so the term is reused instead of created. If the term does not already exist it is create as usual.

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
Hi Eric,
good pointer on needed capability, but change updates auto-generated files which are coming from teh schema definition. We'll let @PaoloPia to look into this on how to get this included to the schema in next versions.

**Comment by eric-scott-owens** [comment]
Am I right in guessing you would only want this in ProvisioningSchema-2015-12.xsd?

**Comment by PaoloPia** [comment]
Hi Eric,
First of all thank you. Yes I think it is better to provide this capability in the current latest implemented schema, which is 201512. The XSD file is already ok, and shouldn't be changed. We simply need to update the formatter for 201512 and the Object Handler. Can you update your PR accordingly? Or would you like that I do the update? Thanks.

**Comment by eric-scott-owens** [comment]
Hi @PaoloPia,
I can get that later tonight.

**Comment by eric-scott-owens** [comment]
Hi @PaoloPia,
Sorry about the delay. This is done along with some improvements to my original code submission.

**Comment by bcage29** [comment]
Hi @eric-scott-owens,
This is great code and works well! The only issue I found is that the source term has to be created before the reused term. Otherwise when the source term goes to be created it errors out.

I think these changes can be added to make it a little more robust. 

**Term.cs**
Create new property for IsSourceTerm

**ObjectTermGroup.cs**
`if (modelTerm.IsReused || modelTerm.IsSourceTerm)` - Line 185
`if (!modelTerm.IsReused && !modelTerm.IsSourceTerm) return new TryReuseTermResult() { Success = false, UpdatedParser = parser };` - Line 335
`if (modelTerm.IsSourceTerm)
{
                    preExistingTerm.ReassignSourceTerm(createdTerm);
                }` -Line 386

**XMLPnPSchemaV201512Formatter.cs**
Update the property setters for IsSourceTerm just as IsResued are set

The only issue is that we have to update the Schema because `<xsd:attribute name="IsSourceTerm" type="xsd:boolean" use="optional" default="true">` is set to true and needs to be false.

**Comment by eric-scott-owens** [comment]
Hi @bcage29,
In walking through a generated template I've found that all instances of the re-used term are marked as re-used, even the source term. Unless I'm missing something I don't think the first two checks are providing anything extra... Can you help me out there?

The last check I like a lot. Currently it's going to let the first one it runs into become the source term. I'm not sure if there are any down sides to this. At least, I haven't found any yet. But, I'm in favor of submitting an update for the schema and swinging back to update this project when the schema update comes through. 

(Currently It doesn't look like the schema marks anything with the IsSourceTerm attribute.)

**Comment by bcage29** [comment]
Hi @eric-scott-owens,
The first check `if (modelTerm.IsReused || modelTerm.IsSourceTerm)` is necessary in order for the source term to be handled as a "reused" term. We essentially want reused and source terms to be created the same way and we will set the source term it has been created. I don't think source terms should be marked with the attribute reused because they are not reused.

The second check `if (!modelTerm.IsReused && !modelTerm.IsSourceTerm) return new TryReuseTermResult() { Success = false, UpdatedParser = parser };` I only added because it had to be there to continue processing. I think you can remove this line completely because the first check makes sure that one of the properties are set to true. This check reiterates the first and would never be true.

The only unfortunate thing is that the schema defaults the IsSourceTerm to true and since that field is not previously used it will cause an issue with this code if the IsSourceTerm attribute is not explicitly defined on all nodes.

**Comment by eric-scott-owens** [comment]
Thanks @bcage29,

I've just verified that even terms marked with IsSourceTerm == true also have IsReused == true. That being the case the first two lines should be covered regardless. 

It sounds like you don't get IsReused == true for terms also marked with IsSourceTerm == true. Can you tell me a little more about the scenario where you're seeing this happen?

**Comment by bcage29** [comment]
I was building my own template and setting the properties and I am guessing that you are generating the template Web.GetProvisioningTemplate()? I think the TermGroup handler ExtractObjects needs a few tweaks because i don't see the xml being built as expected.

**Comment by eric-scott-owens** [comment]
Actually it's right. I attached an inspector to my local SharePoint farm to confirm earlier. The source term is marked as reused in the live site.

**Comment by eric-scott-owens** [comment]
It's also right to default IsSourceTerm to true. That's the SharePoint default and only get's changed when creating a reused term.

**Comment by eric-scott-owens** [comment]
Hello again @bcage29!

I've added support for honoring the IsSourceTerm attribute. It's default is still true (as discussed above). This pull request now also marks this setting in the template so reused terms that are not the source term will have an attribute of IsSourceTerm="false". 

If manually making a provisioning template you can ignore the IsSourceTerm attribute with the effect being that the last one created will be set as the source term (and a minor processing hit for repeatedly changing which one is the source term).

**Comment by PaoloPia** [comment]
Hi Eric,
Thanks for your contribution. The code has been integrated together with schema v.201605. I've also added support for deprecated terms. I will close this PR because I had to manually resolve conflicts. You will be credited for your great contribution. Thanks again!

**Pull request closed without merging**
