### PR TITLE
Bug fixed. Now the Sequence property is also Updated in the Update Cu…

### PR DESCRIPTION
**Pull request by luismanez**
Issue #187 fixed. Included a change that was already done in PR #186 and a new change in ObjectCustomActions.cs that makes the Sequence property being updated.

Please, let me know if I'm doing anything wrong with the PR.

### CODE REVIEW

**Comment by Trickass** [comment]
I have done the same pull request #186. However, I did not include the Provisioning part in it.
This one seems to be the preferred solution.

**Comment by luismanez** [comment]
I saw that. You've fixed a bug and all the credit is for you about that bug. I'm fixing a different bug (related). I'm just including your change trying to don't cause any issue when the admin does the Merge.
Thanks for your fix!

**Comment by erwinvanhunen** [comment]
Good fixes! Thanks! Regarding the merge issue you tried to solve by including the fix from @Trickass : it's actually better to -not- include changes that come from other PRs. Now his PR either would generate a merge conflict, or his PR would be listed as not relevant, as the change is already merged through this PR.

For contributions we keep track of the merged PRs and find the names of people submitting the PRs. Technically speaking @Trickass introduced a fix that will now be attributed to you through this PR. We will take a note however now to make sure that @Trickass will be attributed at the monthly master merge too. 

A better solution would be: pull down the PR from @Trickass to your own branch in your own Repo: add your added code/changes to that branch, commit, and create a new PR from that branch. That way the commit from @Trickass will be retained and attributed to him. I will perform those tasks now so that both of you will be attributed.

**Comment by luismanez** [comment]
Oh God, so sorry @erwinvanhunen and @Trickass I had no idea about how to do it right and I'm too new with Git. How can I pull down a specific PR from other user? If you want, just cancel my PR and I'll start again.
Thanks for your help and my apologies again.

**Comment by erwinvanhunen** [comment]
No worries! :-) I went through the same thing when learning Git :-) It's all fixed now, so no need to create a new PR. To pull down a PR from someone else:

// Create a new branch
git checkout -b <newname> <nameofyourdevelopingbranch>
git remote add <somelabel> <urlofuserrepository>
git fetch <somelabel>
git merge <somelabel>/<branchname>

Then you publish the <newname> branch to you github repo and make a new PR from that one. But as said, it's all done now :-)

**Comment by erwinvanhunen** [comment]
There was a thing with the PR from @Trickass and that is that he was targeting the Master branch of Core. We do not accept PRs on that one so I manually retargeted his commit too while merging both PRs

**Comment by Trickass** [comment]
Oh, my bad there then! :$
Any chance you could tell me how to do it better next time? How do I target another branch?

**Comment by erwinvanhunen** [comment]
No worries about that :-) It's pretty simple to fix, but also easy to miss. I did it myself many times. When you create the PR, at the top of the page you will see your source branch and which branch you're targeting in the PnP-Core repo. You can switch from the master to the dev branch there through a drop-down.

**Comment by luismanez** [comment]
Perfect! many thanks Erwin
@Trickass If it helps, I use to follow this article to do the PR: https://github.com/OfficeDev/PnP/wiki/Preparing-a-contribution-and-letting-the-PnP-core-team-know-via-a-pull-request

Cheers.

**Pull request merged**
