### PR TITLE
Update ObjectHandlerBase.cs

### PR DESCRIPTION
**Pull request by stefvanhooijdonk**
| Q | A |
| --- | --- |
| Bug fix? | yes |
| New feature? | no |
| New sample? | no |
| Related issues? | no (not submitted) |
#### What's in this Pull Request?

Prevent the "url.Replace(webUrlPathAndQuery, "{site}");" from happening when dealing with theme files in the root site collection "/".

### CODE REVIEW

**Comment by PaoloPia** [comment]
Hi,
Thanks for your contribution. Can you expand a little bit more about the purpose of this PR? What is the scenario/bug that it fixes?

Thanks.

**Comment by stefvanhooijdonk** [comment]
When doing an export of the root site collection ( “/” ) with a theme applied, the code changed the file url of a theme file
from
/_layouts/themecatalog/palettefile.spcolor
to
/_layouts/themecatalog{site}palettefile.spcolor

This would then fail when applying to a new site.

The code change prevents this from happening.

--
Groetjes,

Stef

**Comment by jansenbe** [comment]
Thx Stef,

We'll have a look at this PR in the upcoming weeks.

**Comment by jansenbe** [comment]
Hi Stef,

I've tried to repro this by first uploading the following custom theme files:

```xml
<pnp:ProvisioningTemplate ID="composedlook_files" Version="1" xmlns:pnp="http://schemas.dev.office.com/PnP/2015/12/ProvisioningSchema">
  <pnp:Files>
    <pnp:File Src="garagebg.jpg" Folder="_catalogs/theme/15" Overwrite="true" />
    <pnp:File Src="garagelogo.png" Folder="_catalogs/theme/15" Overwrite="true" />
    <pnp:File Src="garagewhite.spcolor" Folder="_catalogs/theme/15" Overwrite="true" />
  </pnp:Files>
</pnp:ProvisioningTemplate>
```
and then applying a custom theme with:
```xml
<pnp:ProvisioningTemplate ID="composedlook_add_2" Version="1" xmlns:pnp="http://schemas.dev.office.com/PnP/2015/12/ProvisioningSchema">
  <!-- Set custom composed look -->
  <pnp:ComposedLook Name="CL_2" Version="1" 
                    BackgroundFile="{sitecollection}/_catalogs/theme/15/garagebg.jpg" 
                    ColorFile="{sitecollection}/_catalogs/theme/15/garagewhite.spcolor"
                    FontFile="" />
</pnp:ProvisioningTemplate>
```
When I then extract a site with this custom theme it is correctly extracted, the code path you want to change is never hit because the references to the theme files in the themecatalog is replaced by the {themecatalog} or {sitecollection}/_catalogs/theme tokens and as such the "If (url.IndexOf(webUrlPathAndQuery, StringComparison.InvariantCultureIgnoreCase) > -1)" never is valid.

What's strange in your comment is the /_layouts/themecatalog reference since the themecatalog should be referenced using the site collection and not filesystem.

For now I'm gonna close this PR, please elaborate more if the above approach isn't working for you.

**Comment by jansenbe** [comment]
Re-opening this PR for additional testing

**Comment by stefvanhooijdonk** [comment]
The situation I tried to resolve was for a ROOT site collection, just like Camilo.

--
Groetjes,

Stef van Hooijdonk

**Comment by jansenbe** [comment]
Have merged the PR, thanks for the additional clarification.

**Pull request merged**
