### PR TITLE
Added a check to see if the foldername contains _catalogs/theme 

### PR DESCRIPTION
**Pull request by Arceau**
If the site is a subsite then added routine that changes the active web to the site collections root web. This enables the provisioning of any files to the root web's theme catalog.

### CODE REVIEW

**Comment by lafe** [comment]
I also have proposed a solution for this issue. See issue #44 and pull request #83.

**Comment by VesaJuvonen** [comment]
Thanks Time for this. Like Lars noted in comments, we have now few different changes on the theme handling, which overlap and we want to get this right for good. Due however resourcing challenges, it seems that we need to postpone processing all theme related fixes for the January master merge.

**Comment by VesaJuvonen** [comment]
Hi Tim,
we are looking into re-implementing the theme handling starting next week and we'll get all theme related PRs processed at that time. Thx for your contributions.

**Comment by VesaJuvonen** [comment]
We have now manually updated this handling due changes in the schema level and decision on how to handle sub site theming. We did decide to ignore theme files in the case of sub site extraction or provisioning, since in worst case scenario you might run into issues by having different sub site templates overriding difference versions of these files in the root web.

This means that if you hare using custom theme in sub sites, you'll need to ensure that you have provisioned needed files to root web. Implementation pretty similar for the content types: since we would have to jump cross site boundaries, there's a risk that this will cause issues - and therefore we will not process these theme files during extraction or provisioning for sub sites. If they exists already in root web, they will be correctly applied to sub site as well.

**Pull request closed without merging**
