### PR TITLE
PrepareCalulatedField added to PrepareField in ObjectListInstance

### PR DESCRIPTION
**Pull request by braegelno5**
In ObjectListInstance we need a rewriting of calculated fields if the formula contains refs fields. The export part is reading a plain english formula from SP with internal names, but on the deploy side we need a formula with [display names]. I have added a PrepareCalulatedField method to the PrepareField method to do this. If we found a formula with '[' or ']' in there we do nothing, because may be the field was build by hand.

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
thx Torsten, looks good. Target to get included to March release.

**Comment by m-carter1** [comment]
We ran into the same issue and unfortunately this fix didn't work for us.

If the formula contains a "[" or "]" it skips it, however we have a formula that contains those characters [] but also has the internal name issue so this errors when provisioning.

Another issue is if the Internal Names are very similar it errors. e.g. FieldName1 and FieldName11

Looking further into the issue with provisioning calculated fields, it seems the issue is the way it's extracting the fields. In the front end (looking at the Sharepoint field online) the formula's show the display names but when we get the provisioning template they have changed to Internal Names. For some reason the SchemaXml on the field has swapped out Display Names for Internal Names but the Formula property does contain the Display names!

I've updated the extracting method on fields to swap out the SchemaXml formula value with the Field Formula value. This now means the calculated fields will provision correctly and this fix is no longer needed.

Pull Request: https://github.com/OfficeDev/PnP-Sites-Core/pull/432

**Comment by asumner** [comment]
If we have a calculated column that used Range[i] for example this fix skips the fix if it sees a square bracket.
The fix uses a search and replace and we can break this again by having similar field names that contain the search target. Whilst fixing "RequiredDate" and "RequiredDateDescription" We'd get "[Required Date]Description" causing an error.

We've put up a fix #432 that requires verification (in our tests all of our broken lists passed), we chose to write the Formula out to the template during its creation, that way, nothing needs to be fixed in the provisioning code, I hope that its a correct approach. Thanks @braegelno5 for helping us home in on the problem! @VesaJuvonen @PaoloPia

**Comment by PaoloPia** [comment]
Hi Torsten,
Thanks for your contribution. Unfortunately the source branch is no more available and consequently I cannot do proper testing of the suggested solution, before merging it. Moreover, it looks like there are conflicts that cannot be easily resolved. Could you please re-submit the changes, if still needed, keeping the source branch alive until after proper testing? Unfortunately, I have to close this PR. Thanks again.

**Pull request closed without merging**
