### PR TITLE
fix SetCustomMasterPageByUrl not setting the property to switch inher…

### PR DESCRIPTION
**Pull request by bryonchan**
…itance of the master page

### CODE REVIEW

**Comment by jansenbe** [comment]
Thx Bryon. 

I manually merged this one as you were targeting the PR to our master branch whereas we normally only accept PR's against our dev branch. Luckily this was a small change and we'll ensure you get credited for this as this indeed is a good catch :-)

**Comment by bryonchan** [comment]
Thanks Jan, it's my first ever PR, I knew there had to be some rookie mistake in there. :)

**Comment by VesaJuvonen** [comment]
Hi Bryon,
can you update your actual name information to your GitHub profile, so that we can provide you credits with your real name. If you have a Twitter account or a blog, you'd like us to reference in monthly communications, just let us know as well. thx.

**Comment by bryonchan** [comment]
Hi, I've updated my name.

Thanks,
Bryon

**Pull request closed without merging**
