### PR TITLE
List Instance Data Rows: Not throwing for exception type Microsoft.SharePoint.SPDuplicateValuesFoundException

### PR DESCRIPTION
**Pull request by olemp**
| Q | A |
| --- | --- |
| Bug fix? | no |
| New feature? | yes |
| New sample? | no |
#### What's in this Pull Request?

In Object Handler List Instance Data Rows, not throwing for exception type Microsoft.SharePoint.SPDuplicateValuesFoundException. 

We want to keep configuration list entries in DataRows with a unique key. As of now, the provisioning template fails if we attempt to add a list item which has a duplicate.

This PR fixes this checking ServerException.ServerErrorTypeName.

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
Hi Ole, initial thinking is that it's not also correct to "eat up the exception" without any notification. We do understand your thinking on this though. We'll have a closer look and will get back to you.

**Comment by okms** [comment]
I've discussed this with @olemp and the usecase for this specific change is as follows: if we have a template with <pnp:DataRows>, all those data rows will be duplicated when re-applying the template. In effect you would have to maintain a "initial" template and an "upgrade" template. 

While there are no great mechanisms to avoid this for happening, the work-around is to use a hidden column with a unique key and enforce unique values turned on.

I absolutely agree that as a minimum the exception needs to be logged as warn or info @VesaJuvonen

**Comment by olemp** [comment]
Any news on this @VesaJuvonen @erwinvanhunen ?

**Comment by jansenbe** [comment]
I've implemented a slightly different approach: in ProvisioningTemplateApplyingInformation there's a flag (IgnoreDuplicateDataRowErrors) that controls the behavior when a duplicate list item exception is thrown. If you set this flag to true then the engine will ignore the duplicate row errors, default is false as that's the current behavior of the engine. I've not merged this PR since my implementation is different but will ensure you guys get the credits for this one. As such the PR will be closed but the feature will be in.

Also we would like to apologize for the long time it took to process this PR...but better late then not all, hope you guys can understand.

Thanks!

**Pull request closed without merging**
