### PR TITLE
Provisioning - Content types added to the list instance should not be removed

### PR DESCRIPTION
**Pull request by artokai**
When PnP Provisioning engine creates new list instances, it should never remove any content types which are configured in the template.

The template could for example contain a document library which should use the  content types "Document" and "CustomDocument". In this case the content type "Document" should not be removed from the library even though the "remove existing content types" -flag is set.

### CODE REVIEW

**Comment by VesaJuvonen** [comment]
Hi Arto,
thanks for the submission on this one. We did do small analyses on this and did not quite get the scenario. There are two different typical scenarios with the content types:

1. Remove Documents from the oob documents library and only leave custom document content type
2. Add new content types and change the default content type for the library

Engine is targeting to support both of these scenarios with support on flagging what should be removed. Due this we did not quite understand the objective of this pull request, so more details would be needed. thx.

**Comment by artokai** [comment]
It might not be the typical use scenario, but if my provisioning template directly says that content types "document" and "contenttypeX" should be included in the library, then I would expect both of the content types to actually appear there (regardless of the remove existing content types -setting).

So removing that Document content type is in my opinion a bug or at least very unexpected behavior...

**Comment by olemp** [comment]
The 'Document' content type is already there so add your custom content type X and set RemoveExistingContentTypes to false?

**Comment by artokai** [comment]
I agree that the same end result can be achieved by not removing the existing content types. 

But I don't like the fact that you need to KNOW that the provisioning engine does not allow you to specify an already existing content type and use the remove existing content types setting at the same time.

To me that combination of settings in the template seems to be totally legal.

**Comment by artokai** [comment]
To further clarify the reason for this pull request...

What would you expect the end result something like the following to be without reading the source code of the provisioning engine? I bet that a most people would think that the content type Document would be available in the library. So currently the engine might "work as designed" but I don't think it "works as expected".

```
<ListInstance name="SomeList" RemoveExistingContentTypes="true">
   <contentTypeBindings>
        <contenttype name="Document"/>
        <contenttype name="SomeOtherType"/>
   </contenTypes>
</ListInstance>
```

I could just leave out the RemoveExistingContentTypes setting, but personally I might really want to put something like that in my templates because it would clearly document my intentions. Having a template like that tells everyone else who might be reading the template, that I really wanted to have that Document ContentType in there and it was not left in the library by mistake.

Furthermore... 

Currently the provisioning engine does not support removing existing content types from existing libraries. It would actually be a nice addition since it would allow me to remove the "Document" content type from the OOTB Documents and replace it with a customer specific one. 

(Let's forget for a moment  the fact that deleting a content type which is in use is not possible)

How would that work if this was actually supported by the engine? It would work just fine the 1st time you applied the template to a site. But with the current rules, it would not be possible to reapply a slightly modified template to the same site again. Even the customized content types would then be "existing content types" and would be removed by the provisioning engine even if those customized content types would be clearly listed in the ContentTypeBindings-section.

Sorry about the long narrative =)

**Comment by VesaJuvonen** [comment]
Hi Arto,
we just talked about this with the Core team and key challenge is that if we would start supporting removing content types in delta handling, we would start having issues on handling all the content. Meaning that you could anyway not remove content type if it has any content associated for it. Therefore we would rather recommend to implement this using extension provider, rather than having native support in the engine. 

We have been having long discussions around the delta handling and updates which we can support. Right now this is just not something what we want to implement, since it will cause additional challenges.

thx. for the suggestion and good discussion around this.

**Comment by braegelno5** [comment]
My question on this: if i have a template with a lot of lists from different content types, all this lists will created from the engine. I say create not update no delta handling! So if all my lists will created they get the list default ct, but this ct is not defined in the template for this list, there is also no handy change to RemoveExistingContentTypes="true" in the template (a lot of lists)..
My suggestion would be, we set RemoveExistingContentTypes to true in the ObectListInstance handler call for CreateList, then we add all createdList.ContentTypes to the contentTypesToRemove List. Every time we select a ct from list template we check to remove this ct from contentTypesToRemove List, and in the end we check on real remove from createdList that this ct from contentTypesToRemove is not the last one.
So we get a 1:1 clean new list from the xml definition. If a ct not exists in this site, the list will have as least the default ct from oob.

**Comment by artokai** [comment]
@braegelno5 Your suggestion could break some existing implementations out there. Some templates might list only the additional custom content types and trust in the fact that the default content types are not removed if the "RemoveExistingContentTypes" flag is not set.

**Comment by braegelno5** [comment]
In my last pr is also sliped some code for this in. Sorry. But the changes there are only for the case where the flag is set to true. So we delete only a not used ct from the list and hold the last one in the list.

**Comment by artokai** [comment]
@braegelno5 I must have misunderstood your comment. I looked at your PR and it actually does pretty much the same thing what I tried to achieve with my pull request. Thanks!

**Pull request closed without merging**
